PORT_IN: 8080
PORT_OUT: 8081

EXTERNAL_SERVER: "localhost"

CCURE_DIR: "./"
CCURE_LOG_PATTERN: ".+./log"

SMTP_SERVER: "smtp.gmail.com:587"
SMTP_USER: "ACSBridgeReporter"
SMTP_PASS: "qmwnebrvt"
MAIL_FROM: "ACSBridgeReporter@gmail.com"
MAIL_TO: ["qwertyman159@gmail.com"]

LOG_FILE: "./ACSBridge.log"
